### ISSUE TITLE
변경된 DB에 맞게 Repository 함수 쿼리문 수정

### ISSUE THREAD

**Issue by sichoi42** [innovationacademy-kr/42cabi_admin#101]
main 서비스의 DB가 변경됨에 따라 admin도 그에 맞게 구동이 될 수 있도록 Repository 함수의 쿼리문을 수정하겠습니다

**Comment by joohongpark** [comment]
모듈별로 포팅 수행
@sichoi42 cabinet, activation, lent
@joohongpark return, search, user

**Comment by sichoi42** [comment]
테스트를 좀 해봤었는데 #105 해당 이슈 말고는 특별한 문제 없는 것 같네요!

**Comment by joohongpark** [comment]
좋습니다! 그러면 해당 이슈는 닫고 TyoeORM 포팅 이슈를 열어서 포팅을 해 볼까요?

**Comment by sichoi42** [comment]
넵 각자 맡았던 모듈 그대로 하면 될 것 같습니다!

**Comment by joohongpark** [comment]
넵넵! 그러면 이슈 만들어 두겠습니다!
