### ISSUE TITLE
특정 사물함 반납 처리 시 floor, section, num이 undefined로 나오는 문제

### ISSUE THREAD

**Issue by sichoi42** [innovationacademy-kr/42cabi_admin#105]
![f7502aea-af24-478a-bef4-76c855e2a96b](https://user-images.githubusercontent.com/83565255/196711857-2feaa84d-b070-45b1-8db0-e6e9cd904ea5.gif)

**📝 DESCRIPTION**
위 영상처럼 admin에서 특정 사물함을 반납 처리하면 `floor`, `section`, `num`이 `undefined`로 나오는 문제가 있습니다. 
그리고 새로고침을 하면 정상적으로 비어있는 사물함 정보가 나타납니다.
network 상태를 보면 반납 후 기존 사물함을 사용하고 있는 user의 `intra_id`로 검색하여 나온 결과를 보여주는 것 같아
추후 프론트 측에서 `cabinet_id`로 검색한 결과를 즉시 뿌려주는 식으로 변경이 필요할 것 같습니다!

**Comment by Oris482** [comment]
PR #107  - 수정했습니다!
