### ISSUE TITLE
로우쿼리 -> TypeORM 적용

### ISSUE THREAD

**Issue by joohongpark** [innovationacademy-kr/42cabi_admin#106]
**📝 DESCRIPTION**
- 로우쿼리에서 TypeORM으로 전환

**☑ TODO**
- [ ] TypeORM 적용
- [ ] 리포지토리 클래스명 기존 협의된대로 일관성있게 적용
@sichoi42 cabinet, activation, lent
@joohongpark return, search, user

**Comment by joohongpark** [comment]
[refactor-#106](https://github.com/innovationacademy-kr/42cabi_admin/tree/refactor-%23106) 브랜치에 TypeORM 적용을 위한 초기화를 해두었습니다.
해당 작업내용을 develop 브랜치에 머지한 다음 각 브랜치를 따서 해당 브랜치에 머지하거나
해당 브랜치에서 브랜치를 각자 딴 다음 모듈별로 포팅작업을 한 다음 각각 머지하고 해당 브랜치를 최종적으로 머지하는 방법 두가지가 있는거 같습니다.
sichoi님은 어느 쪽이 괜찮으신가요?

**Comment by sichoi42** [comment]
후자로 하는게 어떨까요? 저랑 joopark님 작업을 refactor-#106에 머지하고 테스트해보고 괜찮으면 dev에 올리는게 더 좋을 것 같습니다..!

**Comment by joohongpark** [comment]
좋습니다!
