### ISSUE TITLE
FIX: auth값과 activation값 다름

### ISSUE THREAD

**Issue by Oris482** [innovationacademy-kr/42cabi_admin#122]
**📝 DESCRIPTION**
- 노션 API 페이지 
![image](https://user-images.githubusercontent.com/60038526/197975278-32f0e286-306d-49b1-8137-65e170d06706.png)

- 실제 응답값
![image](https://user-images.githubusercontent.com/60038526/197975491-f3f7aa1e-fb53-4e4a-8139-d7d3e1ce0df5.png)

- 맞는 값 확정해서 알려주시면 거기에 맞게 수정하겠습니다!

**Comment by Oris482** [comment]
@joohongpark 메인에서 페널티 없는데도 auth가 0으로 오는거 같은데 한 번 확인 부탁드립니다..!

**Comment by sichoi42** [comment]
> @joohongpark 메인에서 페널티 없는데도 auth가 0으로 오는거 같은데 한 번 확인 부탁드립니다..!

왜 또 로컬에서는 문제가 없는데 메인에서만 그러지 ㅠㅠ 확인해보겠습니다
