### ISSUE TITLE
BUG: 인트라 아이디로 검색했을 때 이전 기록을 불러오지 못하는 경우

### ISSUE THREAD

**Issue by Oris482** [innovationacademy-kr/42cabi_admin#123]
**📝 DESCRIPTION**
- 이전 사용 기록이 있는 유저를 검색했을 때 응답이 빈 값으로 올 때가 있습니다.
- 아까 얘기해주신대로 현재 해당 유저가 user 테이블 초기화 후 아직 로그인을 안해서 못찾는 걸로 보입니다.
- 짐 정리 기간에 특정 사물함이나 유저의 이전 기록을 확인해야 할 일이 많을 것 같은데 수정 가능할 지 확인 부탁드립니다!

**Comment by sichoi42** [comment]
아... Intra_id로 검색했을 때 수정을 안했네요. 바로 처리하겠습니다~
