### ISSUE TITLE
BUG: 사물함 검색시 500 에러

### ISSUE THREAD

**Issue by Oris482** [innovationacademy-kr/42cabi_admin#140]
## 문제 상황
<img width="632" alt="image" src="https://user-images.githubusercontent.com/60038526/198860558-94936efd-8ab5-4c13-8359-4ed231b86424.png">

DB가 바뀌어서 그렇다고 들었습니다!

**Comment by eunbi9n** [comment]
#137 를 이슈를 해결하여 해당 bug도 같이 고쳤습니다!!
