### ISSUE TITLE
서버 죽었을 때 예외처리

### ISSUE THREAD

**Issue by Yoowatney** [innovationacademy-kr/42cabi_admin#46]
**📝 DESCRIPTION**
- search에서 서버를 안 켰을 경우 "입력을 다시 확인해주세요!"라는 문구가 뜨고, 로그인의 경우 "잘못된 계정입니다" || "아이디 또는 비밀번호를 확인해주세요!"라 뜨는데, 어드민이 당황하지 않게 담당자에게 연락해달라는 문구 혹은 알림창이 있으면 좋을 듯 싶습니다. (서버가 죽었을 때는 백엔드가 대응을 해줘야하기 때문에...)
  프론튼 두 분이서 회의해보시고 동일하게 문구나 알림창이 떠주면 어떨까 의견 제시드려봅니다.

**☑ TODO**
- [ ]

**Comment by Oris482** [comment]
저희 까비 서비스처럼 프론트 빌드해서 백 폴더로 옮기고 서버 하나로 돌리게되면 프론트만 살아있는 경우가 있을 수 있나요??
